[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python web/app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

# Environment variables should be under deploy.env section
[deploy.env]
PORT = "5000"
USE_NGROK = "false"
RAILWAY_ENVIRONMENT = "production"
